library:
  source-dirs: src
tests:
  typed-lambda-inference-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-lambda-inference
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- mtl
- containers
- base >= 4.7 && < 5
name: typed-lambda-inference
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/typed-lambda-inference
license: BSD3
executables:
  typed-lambda-inference-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-lambda-inference
description: Please see the README on GitHub at <https://github.com/githubuser/typed-lambda-inference#readme>
